name: 'Create Grade Artifact'
description: 'Creates an artifact showing the results from `go-test` to be consumed by `phpeterson-usf/autograder`'

inputs:
  score:
    description: 'Score produced from a `colmpat/go-test-action` run. In the format `pts_earned/pts_actual`'
    required: true
  due_date:
    description: 'Date the assignment is due. In ISO format (eg. `2023-08-25T23:59:59.999` -> 11:59:59.999 PM on August 25th 2023)'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
